default: &default
  adapter: postgresql
  encoding: unicode
  username: ubuntu
  pool: 5
development:
  <<: *default
  database: the_wall_development
test:
  <<: *default
  database: the_wall_test
production:
  <<: *default
  database: the_wall_production
  password: <%= ENV['THE_WALL_DATABASE_PASSWORD'] %>